### Assignment-1 tokens

In [3]:
text='i love Generative and Agentic Ai'
tokens=text.split()
print(tokens)
print('token count :',len(tokens))

['i', 'love', 'Generative', 'and', 'Agentic', 'Ai']
token count : 6


In [9]:
### Question:- Print every token with its index
text1='i love learning NLP'
tokens1=text1.split()
print(tokens1)
for i ,token in enumerate(tokens1):
    print(i,token)

['i', 'love', 'learning', 'NLP']
0 i
1 love
2 learning
3 NLP


In [11]:
### Question - Find the longest token in the sentence. Machine Learning is amazing
text2='Machine learning is amazing'
token2=text2.split()
print(token2)
largest_token=max(token2,key=len)
largest_token

['Machine', 'learning', 'is', 'amazing']


'learning'

In [12]:
### Question - Find the shortest token.
text2='Machine learning is amazing'
token2=text2.split()
print(token2)
shortest_token=min(token2,key=len)
print(shortest_token)

['Machine', 'learning', 'is', 'amazing']
is


In [13]:
### Question - Count frequency of every token
from collections import Counter
text = "AI AI AI NLP NLP"
tokens = text.split()
freq = Counter(tokens)
print(freq)

Counter({'AI': 3, 'NLP': 2})


In [15]:
text = "AI AI AI NLP NLP ML ML ML DL DL DL DL DL ML NLP GENAI GENAI AGENTIC"
token=text.split()
freq=Counter(token)
freq

Counter({'DL': 5, 'ML': 4, 'AI': 3, 'NLP': 3, 'GENAI': 2, 'AGENTIC': 1})

In [21]:
## Question - Find unique tokens.
text = "AI AI AI NLP NLP ML ML ML DL DL DL DL DL ML NLP GENAI GENAI AGENTIC"
token=text.split()
unique=set(token)
unique

{'AGENTIC', 'AI', 'DL', 'GENAI', 'ML', 'NLP'}

In [25]:
## Question - Create vocabulary from text.
text = "I love AI and NLP"
tokens = text.split()
print(tokens)
vocab = sorted(set(tokens))
print(vocab)


['I', 'love', 'AI', 'and', 'NLP']
['AI', 'I', 'NLP', 'and', 'love']


In [32]:
## Question - Convert tokens into token IDs
for i ,word in enumerate(vocab):
    print(i,word)
for word in tokens:
    print(vocab[word])

0 I
1 AI
2 love
0
2
1


In [28]:
text = "I love AI"
tokens = text.split()
vocab = {word:i for i,word in enumerate(set(tokens))}
token_ids = [vocab[word] for word in tokens]
print(token_ids)

[0, 2, 1]


In [34]:
# Question - Decode token IDs back into text.
# Answer:-
vocab = {
 "I":0,
 "love":1,
 "AI":2
}
reverse_vocab = {v:k for k,v in vocab.items()}
ids = [0,1,2]
sentence = [reverse_vocab[i] for i in ids]
print(" ".join(sentence))

I love AI


In [36]:
# Question - Implement a simple tokenizer class.
# Answer:-
class SimpleTokenizer:
    def tokenize(self,text):
        return text.split()
obj = SimpleTokenizer()
print(obj.tokenize("I love AI"))

['I', 'love', 'AI']


### Embeddings

In [ ]:
## Question - Create manual embeddings for words.
emeddings={'AI':[0.1,0.2,0.3],
            'NLP':[0.4,0.5,0.6]}
print(emeddings['AI'])

[0.1, 0.2, 0.3]


In [41]:
## Question - Convert token IDs into embeddings
import numpy as np
embedding_matrix = np.array([
 [0.1,0.2,0.3],
 [0.4,0.5,0.6],
 [0.7,0.8,0.9]
])
token_ids=[0,2]
emeddings=embedding_matrix[token_ids]
emeddings

array([[0.1, 0.2, 0.3],
       [0.7, 0.8, 0.9]])

[[0.1 0.2 0.3]
 [0.7 0.8 0.9]]
